server:
  address: 127.0.0.1
  port: 28081
spring:
   datasource:
      url: jdbc:mariadb://localhost/bookexchange_db
      username: root
      password: 3972C7fshtTdw9XDr
   jpa:
      hibernate:
         ddl-auto: update
